version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
    #   POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
volumes:
  data:
networks:
  postgres:
    driver: bridge